kind: Service
apiVersion: v1
metadata:
  name: mongo-service
spec:
  selector:
    app: mongose
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 27017
      # Port to forward to inside the pod
      targetPort: 27017
      nodePort: 30017
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongose
  template:
    metadata:
      labels:
        app: mongose
    spec:
      containers:
        - name: mongose
          image: mongo:5.0.1
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: host-volume
            mountPath: /data/db
      volumes:
      - name: host-volume
        persistentVolumeClaim:
          claimName: pvc-hostpath
      nodeSelector:
        mongonode: "true"    
