kind: Service
apiVersion: v1
metadata:
  name: paypal-gateway-service
spec:
  selector:
    app: paypalgatewayse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30053
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paypalgatewayse
  template:
    metadata:
      labels:
        app: paypalgatewayse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: paypalgatewayse
          image: scaredste/paypal-gateway-service:v5.0.4
          ports:
          - containerPort: 8080
            protocol: TCP

