kind: Service
apiVersion: v1
metadata:
  name: resource-service
spec:
  selector:
    app: resourcese
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcese
  template:
    metadata:
      labels:
        app: resourcese
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: resourcese
          image: scaredste/resource-service:v3.0.3
          ports:
            - containerPort: 8080
              protocol: TCP
