kind: Service
apiVersion: v1
metadata:
  name: config-service
spec:
  selector:
    app: configse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30099
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configse
  template:
    metadata:
      labels:
        app: configse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: configse
          image: scaredste/config-service:v5.0.1
          readinessProbe:
            httpGet:
              path: /info
              port: 8080
            initialDelaySeconds: 5
          ports:
          - containerPort: 8080
            protocol: TCP

