kind: Service
apiVersion: v1
metadata:
  name: config-service
spec:
  selector:
    app: configse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configse
  template:
    metadata:
      labels:
        app: configse
    spec:
      containers:
        - name: configse
          image: scaredste/config-service:v1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
