apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: config-deployment-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: config-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: requests_per_second
        target:
          type: Value
          averageValue: 1000
