kind: Service
apiVersion: v1
metadata:
  name: catalog-service
spec:
  selector:
    app: catalogse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod puerto real de la aplicacion
      targetPort: 8080
      # Port accessible outside cluster puerto exterior
      nodePort: 30006
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogse
  template:
    metadata:
      labels:
        app: catalogse
    spec:
      containers:
        - name: catalogse
          image: scaredste/catalog-service:v1.3.0
          ports:
            - containerPort: 8080

