kind: Service
apiVersion: v1
metadata:
  name: catalog-service
spec:
  selector:
    app: catalogse
  ports:
    - protocol: "TCP"
      port: 8080
      #puerto real de la aplicacion
      targetPort: 8080
      #puerto exterior
      nodePort: 30006
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogse
  template:
    metadata:
      labels:
        app: catalogse
    spec:
      containers:
        - name: catalogse
          image: scaredste/catalog-service:v1.2.9
          ports:
            - containerPort: 8080

