kind: Service
apiVersion: v1
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigatewayse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30018
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigatewayse
  template:
    metadata:
      labels:
        app: apigatewayse
    spec:
      containers:
        - name: apigatewayse
          image: scaredste/apigateway-service:v1.0.1
          ports:
            - containerPort: 8080

