kind: Service
apiVersion: v1
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigatewayse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30087
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigatewayse
  template:
    metadata:
      labels:
        app: apigatewayse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: apigatewayse
          image: scaredste/apigateway-service:v4.0.6
          ports:
            - containerPort: 8080
