kind: Service
apiVersion: v1
metadata:
  name: product-service
spec:
  selector:
    app: productse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productse
  template:
    metadata:
      labels:
        app: productse
    spec:
      containers:
        - name: googleauthse
          image: scaredste/product-service:v1.3.1
          ports:
          - containerPort: 8080
            protocol: TCP

