kind: Service
apiVersion: v1
metadata:
  name: product-service
spec:
  selector:
    app: productse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30033
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productse
  template:
    metadata:
      labels:
        app: productse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: productse
          image: scaredste/product-service:v4.0.5
        #  resources:
         #   limits:
          #    cpu: "1"
           # requests:
            #  cpu: 200m
          ports:
          - containerPort: 8080
            protocol: TCP

