kind: Service
apiVersion: v1
metadata:
  name: cart-service
spec:
  selector:
    app: cartse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30036
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartse
  template:
    metadata:
      labels:
        app: cartse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      initContainers:
      - name: wait-for-mongo-service
        image: curlimages/curl:7.78.0
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' http://mongo-service.default.svc:27017 -o /dev/null --max-time 3) -ne 200 ]; do sleep 1; echo 'Waiting for the webserver...'; done"]
      - name: wait-for-config-service
        image: curlimages/curl:7.78.0
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' http://config-service.default.svc:8080/info -o /dev/null --max-time 3) -ne 200 ]; do sleep 1; echo 'Waiting for the webserver...'; done"]
      containers:
        - name: cartse
          image: scaredste/cart-service:v15.0.2
          readinessProbe:
            httpGet:
              path: /info
              port: 8080
            initialDelaySeconds: 5
          ports:
          - containerPort: 8080
            protocol: TCP

