kind: Service
apiVersion: v1
metadata:
  name: cart-service
spec:
  selector:
    app: cartse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30036
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartse
  template:
    metadata:
      labels:
        app: cartse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: cartse
          image: scaredste/cart-service:v2.0.9
          ports:
          - containerPort: 8080
            protocol: TCP

