kind: Service
apiVersion: v1
metadata:
  name: order-service
spec:
  selector:
    app: orderse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30030
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderse
  template:
    metadata:
      labels:
        app: orderse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: orderse
          image: scaredste/order-service:v5.0.1
          ports:
          - containerPort: 8080
            protocol: TCP

