kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  selector:
    app: authse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30019
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authse
  template:
    metadata:
      labels:
        app: authse
    spec:
      containers:
        - name: authse
          image: scaredste/auth-service:v1.0.1
          ports:
            - containerPort: 8080

