kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  selector:
    app: authse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30051
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authse
  template:
    metadata:
      labels:
        app: authse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: authse
          image: scaredste/auth-service:v2.0.3
          ports:
            - containerPort: 8080
              protocol: TCP


