kind: Service
apiVersion: v1
metadata:
  name: delivery-service
spec:
  selector:
    app: deliveryse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30031
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryse
  template:
    metadata:
      labels:
        app: deliveryse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: deliveryse
          image: scaredste/delivery-service:v2.0.3
          ports:
          - containerPort: 8080
            protocol: TCP

