kind: Service
apiVersion: v1
metadata:
  name: account-service
spec:
  selector:
    app: accountse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30038
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountse
  template:
    metadata:
      labels:
        app: accountse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: accountse
          image: scaredste/account-service:v2.0.5
          ports:
            - containerPort: 8080
              protocol: TCP
