kind: Service
apiVersion: v1
metadata:
  name: welcome-service
spec:
  selector:
    app: welcomese
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 80
      nodePort: 30074
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcomese
  template:
    metadata:
      labels:
        app: welcomese
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: welcomese
          image: scaredste/welcome-service:v7.0.3
        #  resources:
         #   limits:
          #    cpu: "1"
           # requests:
            #  cpu: 200m
          ports:
          - containerPort: 8080
            protocol: TCP

