kind: Service
apiVersion: v1
metadata:
  name: inventory-service
spec:
  selector:
    app: inventoryse
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      nodePort: 30035
  type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryse
  template:
    metadata:
      labels:
        app: inventoryse
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
    spec:
      containers:
        - name: inventoryse
          image: scaredste/inventory-service:v5.0.3
          ports:
          - containerPort: 8080
            protocol: TCP
